authors = ["Jake Nulty <nultinator@yahoo.com>"]
name = "ycashcli"
uuid = "5142e1a0-2bad-11ec-2753-cb2deb141c82"
[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
